Repository LP23-1A/E-Commerce-Team-3, pull requests merged in 2024-03, with the labels that each got.

#23 added sidebar
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/globals.css
  frontend/src/app/order/page.tsx
  frontend/src/app/page.tsx
  frontend/src/assets/Incsvg.tsx
  frontend/src/assets/Ordsvg.tsx
  frontend/src/assets/ProSvg.tsx
  frontend/src/assets/SVG.tsx
  frontend/src/assets/SettingsSVG.tsx
  frontend/src/component/Sidebar.tsx
  frontend/src/pages/income/page.tsx
  frontend/src/pages/product/page.tsx
  frontend/src/pages/settings/page.tsx
  frontend/tailwind.config.ts
Labels: Created

#25 model hiiv
  backend/package-lock.json
  backend/package.json
  backend/src/controller/user.ts
  backend/src/middleware/auth.ts
  backend/src/middleware/generate.ts
  backend/src/model/user.ts
Labels: Created

#27 backend index setup hiij duusav
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/utils/data.ts
  backend/tsconfig.json
Labels: Created

#32 product-add product button created
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/product/page.tsx
  frontend/src/app/settings/page.tsx
  frontend/src/assets/Vectr.png
  frontend/src/components/Navbar.tsx
  frontend/src/components/Sidebar.tsx
  frontend/src/components/admin/GeneralInfoIncome.tsx
  frontend/src/components/admin/GeneralInfoOrder.tsx
  frontend/src/components/admin/GeneralInfoUsers.tsx
Labels: Created

#28 added create product crud
  backend/package-lock.json
  backend/package.json
  backend/src/controller/product.ts
  backend/src/index.ts
  backend/src/model/product.ts
  backend/src/router/product.ts
  frontend/package-lock.json
  frontend/package.json
Labels: documentation

#33 create product
  backend/src/controller/product.ts
  backend/src/index.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/product/page.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/ToggleCreateProduct.tsx
Labels: Created

#34 21 feature signup front auth 0
  frontend/package-lock.json
  frontend/package.json
  frontend/public/img/Pinecone Logo.png
  frontend/src/app/page.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/app/step/page.tsx
  frontend/src/components/admin/Login.tsx
Labels: bug

#39 19 feature signup back end with auth 0
  backend/package-lock.json
  backend/package.json
  backend/src/index.ts
  backend/src/middleware/auth.ts
  backend/src/router/user.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/app/step/page.tsx
  frontend/src/components/AuthProvider.tsx
  frontend/src/components/Test.tsx
  frontend/src/components/admin/Login.tsx
Labels: bug

#43 order detail
  frontend/public/Pinecone Logo.png
  frontend/src/app/orderdetail/page.tsx
  frontend/src/assets/Car.tsx
  frontend/src/assets/ChevronDown.tsx
  frontend/src/assets/ChevronLeft.tsx
  frontend/src/assets/IconIncome.tsx
  frontend/src/assets/IconOrder.tsx
  frontend/src/assets/IconUser.tsx
  frontend/src/assets/Image.png
Labels: Created

#42 40 feature order backend and reveal on frontend
  backend/src/controller/order.ts
  backend/src/index.ts
  backend/src/model/order.ts
  backend/src/model/user.ts
  backend/src/router/order.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/order/page.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/OrderDayFilter.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/OrderNavbar.tsx
  frontend/src/components/StatusBar.tsx
  frontend/src/components/ToggleCreateProduct.tsx
Labels: Created

#51 income front
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/income/page.tsx
Labels: bug

#50 47 feature product table
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/addproduct/page.tsx
  frontend/src/app/editproduct/page.tsx
  frontend/src/app/product/page.tsx
  frontend/src/assets/AngilalIcon.tsx
  frontend/src/assets/Arrow.tsx
  frontend/src/assets/ArrowDown.tsx
  frontend/src/assets/DateTrackerIcon.tsx
  frontend/src/assets/Delete.tsx
  frontend/src/assets/DollarIcon.tsx
  frontend/src/assets/Edit.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/ProductList.tsx
  frontend/src/components/ProductNavbarFilterButton.tsx
  frontend/src/components/ProductTableNavbar.tsx
  frontend/src/components/ToggleCreateProduct.tsx
Labels: Created

#52 46 fix order detail
  backend/src/controller/order.ts
  backend/src/model/order.ts
  backend/src/model/product.ts
  frontend/src/app/[id]/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/orderdetail/page.tsx
  frontend/src/app/step/page.tsx
  frontend/src/components/DeliveryDetail.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/PayDetail.tsx
  frontend/src/components/Test.tsx
  package-lock.json
  package.json
Labels: Created

#59 added pages width-full
  frontend/src/app/[id]/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/product/page.tsx
  frontend/src/components/DeliveryDetail.tsx
  frontend/src/components/GeneralInfo.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/OrderNavbar.tsx
  frontend/src/components/PayDetail.tsx
  frontend/src/components/ProductList.tsx
  frontend/src/components/ProductTableNavbar.tsx
Labels: documentation, Created

#54 login page hiiv
  backend/src/controller/user.ts
  backend/src/middleware/auth.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/checkrole/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/step/page.tsx
  frontend/src/components/AuthProvider.tsx
  frontend/src/components/withAuth.tsx
Labels: Created

#62 module bolgoloo
  backend/package.json
Labels: bug

#57 fixed dashboard cards
  frontend/src/app/[id]/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/components/DeliveryDetail.tsx
  frontend/src/components/EditProduct.tsx
  frontend/src/components/GeneralInfoIncome.tsx
  frontend/src/components/GeneralInfoOrder.tsx
  frontend/src/components/GeneralInfoUsers.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/PayDetail.tsx
  frontend/src/components/ToggleDelete.tsx
Labels: Created

#63 backend config
  backend/package.json
  backend/src/index.ts
  backend/tsconfig.json
  backend/vercel.json
Labels: bug

#41 38 feature upload picture to product using s3
  backend/package-lock.json
  backend/package.json
  backend/src/controller/product.ts
  backend/src/index.ts
  backend/src/router/product.ts
  backend/src/utils/data.ts
  backend/src/utils/s3.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/api/upload-image/route.ts
  frontend/src/app/signup/page.tsx
  frontend/src/components/CreateProduct.tsx
  package-lock.json
  package.json
Labels: Created

#67 sidebar code updated
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/[id]/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/components/BestSeller.tsx
  frontend/src/components/Chart.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/DeliveryDetail.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/PayDetail.tsx
  frontend/src/components/Sidebar.tsx
Labels: bug

#76 statusaar ni ymarch aldaagu filterddeg bolson
  frontend/src/app/layout.tsx
  frontend/src/components/OrderByStatusProvider.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/OrderNavbar.tsx
  frontend/src/components/StatusBar.tsx
Labels: Created

#75 73 fix delete product
  frontend/src/components/ProductList.tsx
Labels: Created

#79 13 feature order by filter username and phone
  frontend/src/app/layout.tsx
  frontend/src/app/signup/page.tsx
  frontend/src/assets/Arrow.tsx
  frontend/src/assets/ChevronDown.tsx
  frontend/src/assets/ChevronRight.tsx
  frontend/src/components/OrderDayFilter.tsx
  frontend/src/components/OrderFilterProvider.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/utils/FormatDate.tsx
  frontend/src/components/utils/FormatTime.tsx
Labels: Created

#78 added some changes
  backend/src/controller/mainCategory.ts
  backend/src/controller/product.ts
  backend/src/controller/subCategory.ts
  backend/src/index.ts
  backend/src/model/mainCategory.ts
  backend/src/model/product.ts
  backend/src/model/subCategory.ts
  backend/src/router/mainCategory.ts
  backend/src/router/product.ts
  backend/src/router/subCategory.ts
  frontend/src/app/api/upload-image/route.ts
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/ProductList.tsx
Labels: documentation

#85 82 feature income page
  frontend/src/app/[id]/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/components/OrderDayFilterInc.tsx
  frontend/src/components/OrderHistory.tsx
Labels: Created

#87 login deerh passwordiig ynzlav
  backend/src/controller/user.ts
  frontend/src/app/login/page.tsx
Labels: bug

#91 aldaanuda zasav
  frontend/src/app/[id]/page.tsx
  frontend/src/app/checkrole/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/step/page.tsx
  frontend/src/components/OrderHistory.tsx
  frontend/src/components/OrderNavbar.tsx
  frontend/src/components/StatusBar.tsx
  frontend/src/components/utils/StatusColor.tsx
Labels: bug

#95 userNavbar duusgav
  frontend/src/app/login/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/PayDetail.tsx
  frontend/src/components/userComponents/Navbar.tsx
Labels: Created

#98 chartjs done
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/page.tsx
  frontend/src/components/Chart.tsx
Labels: documentation

#100 dashboard updated
  frontend/src/app/dashboard/page.tsx
Labels: documentation

#102 carousel duusav
  frontend/src/app/page.tsx
  frontend/src/assets/Drop.tsx
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/Navbar.tsx
Labels: Created

#104 footer done
  frontend/src/assets/Facebook.tsx
  frontend/src/components/userComponents/Footer.tsx
Labels: documentation

#106 ynzlav
  backend/src/model/order.ts
  frontend/src/app/[id]/page.tsx
  frontend/src/app/page.tsx
Labels: bug

#108 107 feature ontsloh buteegdhun haruulah mun shineer nemgdsen
  frontend/src/app/[id]/page.tsx
  frontend/src/app/page.tsx
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/HighlightedProduct.tsx
  frontend/src/components/userComponents/LatestProduct.tsx
Labels: Created

#110 login page bolgov
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/login/page.tsx
  frontend/src/app/userLogin/page.tsx
  frontend/src/app/userSign/page.tsx
Labels: Created

#114 111 feature purchase and add on cart navbar
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/app/user/basket/page.tsx
  frontend/src/app/userSign/page.tsx
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/HighlightedProduct.tsx
  frontend/src/components/userComponents/LatestProduct.tsx
  frontend/src/components/userComponents/Navbar.tsx
  frontend/src/components/userComponents/OrderContext.tsx
Labels: Created

#117 delivery heseg post hiigegu ch uruud duussan
  frontend/src/app/user/basket/page.tsx
  frontend/src/app/user/delivery/page.tsx
  frontend/src/components/userComponents/OrderButton.tsx
Labels: Created

#118 112 feaure user homepage navbar
  frontend/src/assets/BasketIcon.tsx
  frontend/src/assets/FavouriteIcon.tsx
  frontend/src/assets/SearchIcon.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
Labels: documentation

#122 added topbar
  frontend/src/app/page.tsx
  frontend/src/components/userComponents/Topbar.tsx
Labels: documentation

#124 added category page and filter products
  frontend/src/app/page.tsx
  frontend/src/app/user/category/page.tsx
  frontend/src/assets/CorrectIcon.tsx
  frontend/src/components/userComponents/Category.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
  frontend/src/components/userComponents/Topbar.tsx
Labels: documentation

#125 119 fixing user bolon order huselt
  backend/src/controller/order.ts
  backend/src/controller/user.ts
  backend/src/middleware/auth.ts
  backend/src/model/order.ts
  backend/src/utils/s3.ts
  frontend/src/app/[id]/page.tsx
  frontend/src/app/user/delivery/page.tsx
  frontend/src/app/user/success/page.tsx
  frontend/src/assets/Check.tsx
  frontend/src/assets/Clock.tsx
  frontend/src/assets/List.tsx
  frontend/src/components/DeliveryDetail.tsx
  frontend/src/components/PayDetail.tsx
  frontend/src/components/userComponents/Navbar.tsx
  frontend/src/components/userComponents/SuccesfulOrder.tsx
Labels: bug, Created

#126 added product detail page
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/components/userComponents/AddtionalInformation.tsx
  frontend/src/components/userComponents/ProductDetail.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
  frontend/src/components/userComponents/Topbar.tsx
Labels: documentation

#131 style
  frontend/src/app/page.tsx
  frontend/src/app/user/basket/page.tsx
  frontend/src/app/user/category/page.tsx
  frontend/src/app/user/delivery/page.tsx
  frontend/src/app/user/success/page.tsx
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/HighlightedProduct.tsx
  frontend/src/components/userComponents/LatestProduct.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
  frontend/src/components/userComponents/Topbar.tsx
Labels: bug

#132 productdetail
  frontend/src/app/user/category/page.tsx
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/HighlightedProduct.tsx
  frontend/src/components/userComponents/LatestProduct.tsx
  frontend/src/components/userComponents/ProductDetail.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
Labels: documentation

#135 carousel editlev
  frontend/src/app/globals.css
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/HighlightedProduct.tsx
Labels: Created

#136 removed log and deleted unused files
  backend/src/controller/product.ts
  backend/src/utils/s3.ts
  frontend/src/app/product/page.tsx
  frontend/src/app/user/category/page.tsx
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/EditProduct.tsx
  frontend/src/components/ProductFilterByCategory.tsx
  frontend/src/components/ProductFilterContext.tsx
  frontend/src/components/ProductList.tsx
  frontend/src/components/ProductTableNavbar.tsx
  frontend/src/components/ToggleDelete.tsx
  frontend/src/components/userComponents/Carousel.tsx
  frontend/src/components/userComponents/HighlightedProduct.tsx
  frontend/src/components/userComponents/LatestProduct.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
  frontend/src/components/userComponents/SuccesfulOrder.tsx
Labels: documentation

#139 duusav
  frontend/Dockerfile
  frontend/src/app/[id]/page.tsx
  frontend/src/app/checkrole/page.tsx
  frontend/src/app/dashboard/page.tsx
  frontend/src/app/income/page.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/order/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/product/page.tsx
  frontend/src/app/step/page.tsx
  frontend/src/app/user/delivery/page.tsx
  frontend/src/app/user/productDetail/page.tsx
  frontend/src/app/userLogin/page.tsx
  frontend/src/app/userSign/page.tsx
  frontend/src/components/BestSeller.tsx
  frontend/src/components/Chart.tsx
  frontend/src/components/CreateProduct.tsx
  frontend/src/components/EditProduct.tsx
  frontend/src/components/ProductFilterByCategory.tsx
  frontend/src/components/ProductForm.tsx
  frontend/src/components/ProductList.tsx
  frontend/src/components/StatusBar.tsx
  frontend/src/components/userComponents/Category.tsx
  frontend/src/components/userComponents/ProductListByCategory.tsx
  package.json
Labels: bug
